spring:
  config:
    activate:
      on-profile: test

wiremock:
  server:
    port: 8089

logging:
  level:
    org.springframework: DEBUG
    com.kanionland: DEBUG
    feign: DEBUG

jwt:
  secret: ${JWT_SECRET:31qRand0mdYSYgM=}
