server:
  port: 8090

jwt:
  secret: your-256-bit-secret

spring:
  activemq:
    broker-url: tcp://localhost:65130
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
    queue:
      game-session: game-session-queue

jms:
  queue:
    game-session: game-session-queue
