spring:
  config:
    activate:
      on-profile: local
  security:
    user:
      name: user
      password: localpass

server:
  port: 8090

logging:
  level:
    org.springframework: DEBUG
    com.kanionland: DEBUG

jwt:
  secret: ${JWT_SECRET}